### ISSUE TITLE
Double headline?

### ISSUE THREAD

**Issue by jproctor** [ebsco/edsapi-drupal-plugin#10]
Running stock Bartik theme, it was the case before your recent changes that clicking through to a record showed the blue banner twice. This seems to be fixed.

But the title of the record is still presented twice, which feels odd:

![screen shot 2018-02-19 at 4 24 10 pm](https://user-images.githubusercontent.com/363484/36397575-5a3b0962-1591-11e8-8090-90fad51ef2b4.png)

Here’s the relevent snip of HTML (with improvised indentation so I could try to guess what was going on):
```html
    <h1 class="title page-title">Harry Potter : the story of a global business phenomenon / Susan Gunelius.</h1>
  </div>
</div>
<div class="ebsco-record detailrecord-2columns">
  <div>
    <div class="detailrecord-links">
      <ul class="external-links">
        <li><a href='http://proxy.example.com:2048/login?url=http://search.ebscohost.com/login.aspx?direct=true&site=eds-live&db=cat00321a&AN=fivecol.005035519'>View in EDS</a></li>
        <img src="" />
        <img src="" />
      </ul>
    </div>
    <div class="detailrecord-recordmetadata">
      <h1>Harry Potter : the story of a global business phenomenon / Susan Gunelius.</h1>
      <div class="record-toolbar">
        <div class="floatright">#1 of <a href="/ebsco/detailedrecord?id=fivecol.005035519%7Ccat00321a&op=Next" class="_record_link">Next &raquo;</a></div>
      </div>
```

(Also, both being `<h1>`s feels kinda fishy.)

While I’m nitpicking presentation, I notice at the bottom of that page, if I’m not logged in, a rogue period before “Login”:
> The full text cannot be displayed to guests.
> .**[Login](https://example.com/user) for full access.**

**Comment by bmckinney** [comment]
@jproctor this should be adjusted in 0.2.0 release as well - nitpicking is actually much appreciated!
