### ISSUE TITLE
Drupal 9 compatibility

### ISSUE THREAD

**Issue by jproctor** [ebsco/edsapi-drupal-plugin#34]
Is there a plan for Drupal 9 compatibility? This module isn’t the only thing blocking the upgrade for me, but that list keeps getting shorter.

This report is from the [Upgrade Status module](https://www.drupal.org/project/upgrade_status), v 2.7, running in Drupal core 8.9.0 (slightly reformatted for GitHub):

## EBSCO Discovery Service
Scanned on Fri, 06/05/2020 - 11:05.

11 errors found. 5 warnings found. Avoid some manual work by using drupal-rector
for fixing issues automatically or Upgrade Rector to generate patches.

### web/modules/contrib/edsapi-drupal8-plugin/ebsco.module:
STATUS | LINE | MESSAGE
------ | ---- | -------
Fix now | 307 | Call to deprecated function drupal_get_destination(). Deprecated in drupal:8.0.0 and is removed from drupal:9.0.0. Use the redirect.destination service.
Fix now | 715 | Call to deprecated function drupal_get_destination(). Deprecated in drupal:8.0.0 and is removed from drupal:9.0.0. Use the redirect.destination service.
Fix now | 716 | Call to deprecated function drupal_get_destination(). Deprecated in drupal:8.0.0 and is removed from drupal:9.0.0. Use the redirect.destination service.
Fix now | 1144 | Call to deprecated function drupal_get_destination(). Deprecated in drupal:8.0.0 and is removed from drupal:9.0.0. Use the redirect.destination service.
Fix now | 1273 | Call to deprecated function check_url(). Deprecated in drupal:8.0.0 and is removed from drupal:9.0.0. Use UrlHelper::stripDangerousProtocols() or UrlHelper::filterBadProtocol() instead. UrlHelper::stripDangerousProtocols() can be used in conjunction with \Drupal\Component\Render\FormattableMarkup  and an @-variable placeholder which will perform the necessary escaping. UrlHelper::filterBadProtocol() is functionality equivalent to check_url() apart from the fact it is protected from double escaping bugs. Note that this method no longer marks its output as safe.

### web/modules/contrib/edsapi-drupal8-plugin/lib/EBSCODocument.php:
STATUS | LINE | MESSAGE
------ | ---- | -------
Fix later | 375 | Call to deprecated function pager_default_initialize(). Deprecated in drupal:8.8.0 and is removed from drupal:9.0.0. Use \Drupal\Core\Pager\PagerManagerInterface->defaultInitialize() instead.
Fix with rector | 399 | Call to deprecated function drupal_render(). Deprecated in drupal:8.0.0 and is removed from drupal:9.0.0. Use the 'renderer' service instead.

> Aside: it is possible to fix pager initialization now; see sample code in [d.o #3099064](https://www.drupal.org/project/drupal/issues/3099064)

### web/modules/contrib/edsapi-drupal8-plugin/src/Controller/EbscoController.php:
STATUS | LINE | MESSAGE
------ | ---- | -------
Fix now  | 74   | Call to deprecated function drupal_get_destination(). Deprecated in drupal:8.0.0 and is removed from drupal:9.0.0. Use the redirect.destination service.
Fix with rector | 75   | Call to deprecated method url() of class Drupal. Deprecated in drupal:8.0.0 and is removed from drupal:9.0.0. Instead create a \Drupal\Core\Url object directly, for example using Url::fromRoute().
Fix now  | 97   | Call to deprecated function drupal_get_destination(). Deprecated in drupal:8.0.0 and is removed from drupal:9.0.0. Use the redirect.destination service.
Fix now  | 103  | Call to deprecated function drupal_get_destination(). Deprecated in drupal:8.0.0 and is removed from drupal:9.0.0. Use the redirect.destination service.
Fix with rector | 104   | Call to deprecated method url() of class Drupal. Deprecated in drupal:8.0.0 and is removed from drupal:9.0.0. Instead create a \Drupal\Core\Url object directly, for example using Url::fromRoute().

### web/modules/contrib/edsapi-drupal8-plugin/src/Form/EBSCOAPI.php:
STATUS | LINE | MESSAGE
------ | ---- | -------
Check manually | | Class Drupal\ebsco\EBSCOAPI was not found while trying to analyse it - autoloading is probably not configured properly. 

### web/modules/contrib/edsapi-drupal8-plugin/src/Form/EBSCODocument.php:
STATUS | LINE | MESSAGE
------ | ---- | -------
Check manually | | Class Drupal\ebsco\EBSCODocument was not found while trying to analyse it - autoloading is probably not configured properly. 

### web/modules/contrib/edsapi-drupal8-plugin/src/Plugin/ebsco_eds.php:
STATUS | LINE | MESSAGE
------ | ---- | -------
Check manually | | Class Drupal\ebsco\eds\ebscoEDSForm was not found while trying to analyse it - autoloading is probably not configured properly. 

### web/modules/contrib/edsapi-drupal8-plugin/ebsco.info.yml:
STATUS | LINE | MESSAGE
------ | ---- | -------
Check manually | 0 | Add `core_version_requirement: ^8 \|\| ^9` to modules/contrib/edsapi-drupal8-plugin/ebsco.info.yml to designate that the module is compatible with Drupal 9. See https://drupal.org/node/3070687.

**Comment by kelsonthony** [comment]
Hello @jproctor 
Now we have a new Release to Drupal 9 available.

https://github.com/ebsco/edsapi-drupal8-plugin/releases/tag/9
