### ISSUE TITLE
Cached search result presented

### ISSUE THREAD

**Issue by jproctor** [ebsco/edsapi-drupal-plugin#8]
With the latest code (pulled into my dev instance a few minutes ago), and not logged into Drupal, when I search for something (basic search block) and click to see the first result, I can see it.

I do get “#​1 of [Next »](https://example.com/ebsco/detailedrecord?id=abc123&op=Next)” (not the real URL) at the top, which feels like a second number is missing. 

Here’s the real trouble: if I click that “Next »”, or if I go back (thanks for fixing that!) and click the second entry, I still get the first entry unless I rebuild Drupal’s cache before I click.

Is this your module not playing nice with my cache, or my cache not playing nice with your module? (Or both?) Changing only the query string seems like a pretty common thing to do with URLs, so I’m a little surprised it doesn’t just work out of the box.

**Comment by kelsonthony** [comment]
Hello @jproctor and @bmckinney 
I tested several times here on instance local, anonymous tab and guest mode and it works well.
do you check you drupal cache? 
Please, could you watch this video below?
https://www.screencast.com/t/k9TdWgCP2DO 

Thank you.

**Comment by kelsonthony** [comment]
Issue solved
