### ISSUE TITLE
“Next” is broken

### ISSUE THREAD

**Issue by jproctor** [ebsco/edsapi-drupal-plugin#9]
Same scenario as #8 , if I rebuild cache while viewing the first record and then successfully navigate to the second record by clicking “Next »”, I see two problems:

1. It is also presented as “#1 of [Next »](https://example.com/ebsco/detailedrecord?id=abc456&op=Next)” (not the real URL).

2. No matter which record I start with, including the second record (or the fifth, or whatever), “Next »” _always_ takes me to the second record.

**Comment by bmckinney** [comment]
@jproctor thanks, this should be fixed in 0.2.0 release (as well as #8) - let me know when you have a chance to test and confirm

**Comment by kelsonthony** [comment]
Hello @jproctor @bmckinney 
I just checked and this issue is now fixed

please, see the video below
https://www.screencast.com/t/ahvhttlUGg 

Thank you.

**Comment by kelsonthony** [comment]
Issue solved.
